import torch

from .volume_preserving import VolumePreserving


class TaylorGreenVortex(VolumePreserving):
    """Volume-preserving flow on the unit torus ``[0,1]^2`` generated by
    integrating the Taylor-Green velocity field for ``total_time`` seconds
    using ``num_steps`` of classical RK4.

    The velocity field is
        u(x, y) =  amplitude · sin(π k x) cos(2π k y)
        v(x, y) = -amplitude · cos(π k x) sin(2π k y)
    which is divergence-free and 1-periodic in both axes, so its time-T flow
    is a volume-preserving diffeomorphism of the unit torus.

    Parameters
    ----------
    domain_sample_size : int
        Forwarded to the base ``Regularizer`` (``n_per_dim``).
    total_time : float
        Total integration time of the flow.
    num_steps : int
        Number of RK4 steps; step size is ``total_time / num_steps``.
    amplitude : float
        Velocity amplitude ``A`` above.
    wavenumber : int
        Integer wave number ``k``. Must be an integer for periodicity on the
        unit torus. Defaults to 1, giving the classical single-vortex pattern.
    """

    def __init__(
        self,
        domain_sample_size: int,
        total_time: float = 0.1,
        num_steps: int = 16,
        amplitude: float = 1.0,
        wavenumber: int = 1,
    ) -> None:
        super().__init__(domain_sample_size=domain_sample_size)
        self.total_time = float(total_time)
        self.num_steps = int(num_steps)
        self.amplitude = float(amplitude)
        if int(wavenumber) != wavenumber:
            raise TypeError(
                f"wavenumber must be an integer for periodicity on the unit "
                f"torus; got {wavenumber!r}"
            )
        self.wavenumber = int(wavenumber)

    def velocity(self, coords: torch.Tensor) -> torch.Tensor:
        """Analytical Taylor-Green velocity at ``coords`` of shape ``(..., 2)``."""
        omega = torch.pi * self.wavenumber
        x = coords[..., 0]
        y = coords[..., 1]
        sin_x, cos_x = torch.sin(omega * x), torch.cos(omega * x)
        sin_y, cos_y = torch.sin(omega * y), torch.cos(omega * y)
        u = self.amplitude * sin_x * cos_y
        v = -self.amplitude * cos_x * sin_y
        return torch.stack([u, v], dim=-1)

    def transform(self, coords: torch.Tensor) -> torch.Tensor:
        if coords.shape[-1] != 2:
            raise ValueError(
                f"TaylorGreenVortex is 2D; got coords of shape {tuple(coords.shape)}"
            )
        dt = self.total_time / self.num_steps
        x = coords
        for _ in range(self.num_steps):
            k1 = self.velocity(x)
            k2 = self.velocity(x + 0.5 * dt * k1)
            k3 = self.velocity(x + 0.5 * dt * k2)
            k4 = self.velocity(x + dt * k3)
            x = x + (dt / 6.0) * (k1 + 2.0 * k2 + 2.0 * k3 + k4)
        return x % 1.0  # wrap to the unit torus
