
_target_: infidictionary.networks.NerfSpatioTemporalField
spatial_hidden_dims:
  - 256
  - 256
  - 256
activation:
  _target_: torch.nn.SiLU
  _partial_: true
nerf_n_levels: 8
nerf_n_base: 64
nerf_freq_min: 1.0
nerf_freq_max: 64.0
