# @package _global_
#
# Usage:
#   python reg_cob.py +euclidean_group=mirroring

defaults:
  - _self_

initial_dictionary:
  num_channels: 1
  steepness: 1.01
  tiebreak_eps: 1.0e-3
  # pmf_mode: uniform
  # truncation: 20 ???


neural_isometry:
  channels_dim: 1
  rank: 10
  base_acceleration: 1000.
  atom_shuffling_K: 20 # important to think about
  scalar_field_partial: null
  use_power_law: False 


model_state_kwargs:
  num_steps: 100

tail_probability: 0.0001 # 0.011
num_tail_samples: 32 # 0
grad_accumulation_steps: 8
max_grad_norm: 1.0

regularizer:
  _target_: infidictionary.regularizers.EuclideanGroup
  domain_sample_size: 64
  translation: [0, 0]
  rotation_quarter_turns: [0, 0]
  mirrors: [True, False]

checkpointing:
  checkpoint_dir: outputs/checkpoints
  checkpoint_every_n_steps: 2

wandb:
  project: BasisLearning-euclidean-group
  tags:
    method: euclidean_group
